T/138 responses controller update response
Devscord-Team/Watchman pull request #203
Opened 2022-03-22 20:48 UTC by Tramp2115

2022-03-22 20:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/TestObjectFactories/TestControllersFactory.cs
> +    }
formatowanie kodu

2022-03-23 19:49 UTC, Marcin99b requested changes

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            var contexts = this.testContextsFactory.CreateContexts(serverId, 1, 1);
zmienna serverId nie ma sensu, możesz później używać contexts.Server.Id

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +        public async Task UpdateResponse_ShouldNotFindAnyResponse(UpdateResponseCommand command)
> ShouldNotFindAnyResponse

dodaj sprawdzenie czy wysyła wiadomość że nie znalazło

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +        public async Task UpdateResponse_ShouldNotFindAnyResponse(UpdateResponseCommand command)
> ShouldNotFindAnyResponse

dodaj sprawdzenie czy wysyła wiadomość że nie znalazło

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.UpdateResponse(expectedResponse.Id, It.IsAny<string>()), Times.Never);
w update sprawdzaj id jako It.IsAny
tutaj nie powinno być żadnej aktualizacji

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.UpdateResponse(expectedResponse.Id, It.IsAny<string>()), Times.Never);
w update sprawdzaj id jako It.IsAny
tutaj nie powinno być żadnej aktualizacji

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.RemoveResponse(It.IsAny<string>(), It.IsAny<ulong>()), Times.Once);
dodałbym sprawdzenie czy używa raz dla konkretnego ID serwera 

i nigdy dla serwera różnego niż aktualny

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.RemoveResponse(It.IsAny<string>(), It.IsAny<ulong>()), Times.Once);
dodałbym sprawdzenie czy używa raz dla konkretnego ID serwera 

i nigdy dla serwera różnego niż aktualny

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +        }
możesz wrzucić sprawdzenie czy na pewno nie aktualizuje i nie usuwa

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +        }
możesz wrzucić sprawdzenie czy na pewno nie aktualizuje i nie usuwa

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.UpdateResponse(expectedResponse.Id, It.IsAny<string>()), Times.Once);
możesz dodać sprawdzenie czy na pewno nie aktualizuje innego response niż aktualny ID serwera

2022-03-23 19:49 UTC, Marcin99b commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            responsesServiceMock.Verify(x => x.UpdateResponse(expectedResponse.Id, It.IsAny<string>()), Times.Once);
możesz dodać sprawdzenie czy na pewno nie aktualizuje innego response niż aktualny ID serwera

2022-03-23 21:16 UTC, DavidPL-coder commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            var expectedResponse = new DomainModel.Responses.Response("test", "test", (ulong)43, new string[] { "test" });
```suggestion
            var expectedResponse = new DomainModel.Responses.Response("test", "test", ul43, new string[] { "test" });
```

2022-03-23 21:18 UTC, DavidPL-coder commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            var expectedResponse = new DomainModel.Responses.Response("test", "test", (ulong)43, new string[] { "test" });
daj u43 zamiast (ulong)43

2022-03-23 21:43 UTC, DavidPL-coder commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            var expectedResponse = new DomainModel.Responses.Response("test", "test", (ulong)43, new string[] { "test" });
To moim zdaniem może iść z autodata (swoją drogą zapis (ulong)43 wygląda gorzej niż ul43).

2022-03-23 21:52 UTC, DavidPL-coder commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +            var expectedResponse = new DomainModel.Responses.Response("test", "test", (ulong)43, new string[] { "test" });
to może iść z autodata.

2022-03-23 21:58 UTC, DavidPL-coder requested changes

2022-03-23 21:58 UTC, DavidPL-coder commented on Watchman.Discord.UnitTests/Responses/ResponsesControllerTests.cs
> +               .Returns(Task.FromResult(new DomainModel.Responses.Response("test", command.Message, 43u, new string[] { "test" })));
mogłeś użyć expectedResponse zamiast tego new DomainModel.Responses.Response(...).

2022-03-30 13:32 UTC, Marcin99b requested changes

2022-03-31 16:31 UTC, Marcin99b approved these changes

2022-03-31 16:32 UTC, Marcin99b requested changes

2022-03-31 16:32 UTC, Marcin99b commented on Watchman.Discord.UnitTests/TestObjectFactories/TestControllersFactory.cs
> +    }
nie poprawione nadal

2022-03-31 19:25 UTC, closed without merging